services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongo:27017/mydb?authSource=mydb&replicaSet=rs0
    ports:
      - "${PORT}:${PORT}"

    depends_on:
      mongo:
        condition: service_healthy

    environment:
      PORT: ${PORT}
      DATABASE_URL: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongo:27017/mydb?authSource=mydb&replicaSet=rs0

    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

  mongo:
    image: mongo-prisma

    build:
      context: ./docker/mongo

    ports:
      - "27017:27017"

    command: ["mongod", "--auth", "--bind_ip_all", "--replSet", "rs0"]

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}

    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    healthcheck:
      test: >
        mongosh --username ${MONGO_USERNAME} --password ${MONGO_PASSWORD} --authenticationDatabase admin --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }"
      interval: 5s
      timeout: 30s
      retries: 30

volumes:
  mongo-data:
